name: Check Style and Unit Tests

on:
  push:
    branches:
      - branch_3_GR
  pull_request:
    branches:
      - branch_3_GR

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
      - name: Check Style
        run: pycodestyle --first Portfolio_Tracker/*.py

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover tests
          python -m coverage run -m unittest discover tests
          python -m coverage report
          python -m coverage html
      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov
